Fix dev tool
I encountered the following error. This is my attempt to fix it.:
 + apt update
-------------------- OMITTED 22 lines --------------------
[1730222716] Reading package lists...
[1730222716] Building dependency tree...
[1730222716] Reading state information...
[1730222716] 35 packages can be upgraded. Run 'apt list --upgradable' to see them.
[1730222710]
 + apt install -y universal-ctags
-------------------- OMITTED 28 lines --------------------
[1730222719] update-alternatives: warning: skip creation of /usr/share/man/man1/ctags.1.gz because associated file /usr/share/man/man1/ctags-universal.1.gz (of link group ctags) doesn't exist
[1730222719] update-alternatives: using /usr/bin/ctags-universal to provide /usr/bin/etags (etags) in auto mode
[1730222719] update-alternatives: warning: skip creation of /usr/share/man/man1/etags.1.gz because associated file /usr/share/man/man1/ctags-universal.1.gz (of link group etags) doesn't exist
[1730222719] Processing triggers for libc-bin (2.39-0ubuntu8.3) ...
[1730222710]
 + pip3 install -e .
-------------------- OMITTED 529 lines --------------------
      copying tiktoken/model.py -> build/lib.linux-aarch64-cpython-312/tiktoken
      copying tiktoken/load.py -> build/lib.linux-aarch64-cpython-312/tiktoken
      copying tiktoken/registry.py -> build/lib.linux-aarch64-cpython-312/tiktoken
      creating build/lib.linux-aarch64-cpython-312/tiktoken_ext
      copying tiktoken_ext/openai_public.py -> build/lib.linux-aarch64-cpython-312/tiktoken_ext
      running egg_info
      writing tiktoken.egg-info/PKG-INFO
      writing dependency_links to tiktoken.egg-info/dependency_links.txt
      writing requirements to tiktoken.egg-info/requires.txt
      writing top-level names to tiktoken.egg-info/top_level.txt
      reading manifest file 'tiktoken.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching 'Makefile'
      adding license file 'LICENSE'
      writing manifest file 'tiktoken.egg-info/SOURCES.txt'
      copying tiktoken/py.typed -> build/lib.linux-aarch64-cpython-312/tiktoken
      running build_ext
      running build_rust
      error: can't find Rust compiler
      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
      To update pip, run:
          pip install --upgrade pip
      and then retry package installation.
      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchai...
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tiktoken
[1730222742]   Building wheel for chroma-hnswlib (pyproject.toml): started
[1730222763]   Building wheel for chroma-hnswlib (pyproject.toml): finished with status 'done'
[1730222763]   Created wheel for chroma-hnswlib: filename=chroma_hnswlib-0.7.3-cp312-cp312-linux_aarch64.whl size=2178964 sha256=1a26043a69cc2d6c6e0e198eadc519d025d174f53e42e8425a26c0d735a0f447
[1730222763]   Stored in directory: /root/.cache/pip/wheels/6d/14/b5/68c4f2e056600c0348a94efba92dc975686ab72b714e0ca3d6
[1730222763]   Building wheel for pypika (pyproject.toml): started
[1730222763]   Building wheel for pypika (pyproject.toml): finished with status 'done'
[1730222763]   Created wheel for pypika: filename=PyPika-0.48.9-py2.py3-none-any.whl size=53725 sha256=94db275cb1863ac0f94f866db01e09dac0a315c7d79517f4e9eff39b47697716
[1730222763]   Stored in directory: /root/.cache/pip/wheels/d5/3d/69/8d68d249cd3de2584f226e27fd431d6344f7d70fd856ebd01b
[1730222763] Successfully built mentat fire chroma-hnswlib pypika
[1730222763] Failed to build tiktoken
ERROR: Could not build wheels for tiktoken, which is required to install pyproject.toml-based projects